name: Expired Issues Closure

on:
  schedule:
  - cron: 0 5 * * *

jobs:
  cycle-weekly-close:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Close expired "duplicated" issues
      uses: piroor/close-expired-issues-based-on-label@master
      env:
        LABEL: "duplicated"
        EXCEPTION_LABELS: "needs-triage"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EXPIRE_DAYS: 7
    - name: Close expired "expired" issues
      uses: piroor/close-expired-issues-based-on-label@master
      env:
        LABEL: "expired"
        EXCEPTION_LABELS: "needs-triage"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EXPIRE_DAYS: 7
    - name: Close expired "wontfix" issues
      uses: piroor/close-expired-issues-based-on-label@master
      env:
        LABEL: "wontfix"
        EXCEPTION_LABELS: "needs-triage"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EXPIRE_DAYS: 7
    - name: Close expired "out of scope" issues
      uses: piroor/close-expired-issues-based-on-label@master
      env:
        LABEL: "out of scope"
        EXCEPTION_LABELS: "needs-triage"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EXPIRE_DAYS: 7
    - name: Close expired "intentional" issues
      uses: piroor/close-expired-issues-based-on-label@master
      env:
        LABEL: "intentional"
        EXCEPTION_LABELS: "needs-triage"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EXPIRE_DAYS: 7
    - name: Close expired "invalid" issues
      uses: piroor/close-expired-issues-based-on-label@master
      env:
        LABEL: "invalid"
        EXCEPTION_LABELS: "needs-triage"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EXPIRE_DAYS: 7

    - name: Close expired "has-workaround" issues
      uses: piroor/close-expired-issues-based-on-label@master
      env:
        LABEL: "has-workaround"
        EXCEPTION_LABELS: "Firefox-issue, help wanted, in-progress, needs-triage"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EXPIRE_DAYS: 14
        EXTEND_DAYS_BY_REOPENED: 7
        EXTEND_DAYS_BY_COMMENTED: 7
    - name: Close expired "fixed" issues
      uses: piroor/close-expired-issues-based-on-label@master
      env:
        LABEL: "fixed"
        EXCEPTION_LABELS: "needs-triage"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EXPIRE_DAYS: 14
        EXTEND_DAYS_BY_REOPENED: 7
        EXTEND_DAYS_BY_COMMENTED: 7
    - name: Close expired "maybe fixed" issues
      uses: piroor/close-expired-issues-based-on-label@master
      env:
        LABEL: "maybe fixed"
        EXCEPTION_LABELS: "in-progress, needs-triage"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EXPIRE_DAYS: 14
        EXTEND_DAYS_BY_REOPENED: 7
        EXTEND_DAYS_BY_COMMENTED: 7
    - name: Close expired "stale" issues
      uses: piroor/close-expired-issues-based-on-label@master
      env:
        LABEL: "stale"
        EXCEPTION_LABELS: "needs-triage"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EXPIRE_DAYS: 14
        EXTEND_DAYS_BY_REOPENED: 7
        EXTEND_DAYS_BY_COMMENTED: 7

    - name: mark "help wanted" issues as stale
      uses: piroor/auto-mark-as-stale-issues@main
      env:
        LABEL: "stale"
        EXCEPTION_LABELS: "needs-triage"
        CANDIDATE_LABELS: "help wanted"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EXPIRE_DAYS: 30
        EXTEND_DAYS_BY_COMMENTED: 7
        COMMENT: This issue has been labeled as "stale" due to no response by the reporter within 1 month (and 7 days after last commented by someone). And it will be closed automatically 14 days later if not responded.
    - name: mark "Firefox-issue" issues as stale
      uses: piroor/auto-mark-as-stale-issues@main
      env:
        LABEL: "stale"
        EXCEPTION_LABELS: "needs-triage"
        CANDIDATE_LABELS: "Firefox-issue"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EXPIRE_DAYS: 365
        EXTEND_DAYS_BY_COMMENTED: 7
        COMMENT: This issue has been labeled as "stale" due to no response by the reporter within 1 year (and 7 days after last commented by someone). And it will be closed automatically 14 days later if not responded.
