name: CI/CD

on: [push]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: prepare manifest.json with a revision number
      run: |
        cp webextensions/manifest.json ./
        version=$(cat manifest.json | jq -r ".version" | sed -r -e "s/$/.$(git log --oneline | wc -l)/")
        cat manifest.json | jq ".version |= \"$version\"" > webextensions/manifest.json
    - name: build xpi
      run: make
    - uses: actions/upload-artifact@master
      with:
        name: treestyletab-we.xpi
        path: treestyletab-we.xpi
